import requests


data = {
        'study_id':1234, 
        'baby_apgar_score_one_min':7,
        'baby_apgar_score_five_min':9,
        'baby_condition_yes_eos_los':'Eos',
        'baby_condition_lga_suspect':'NA',
        'baby_gestational_age':32,
        'baby_weight_at_birth':1.23,
        'baby_weight_at_admission':1.4,
        'mother_age':21,
        'mother_weight':45,
        'mother_height':4.6,
        'mother_haemoglobin':11.8,
        'mother_bmi':23.91,
        'maternal_blood_pressure':110,
        'maternal_blood_pressure_diastolic':80,
        'maternal_fever':97.6,
        'maternal_thyroid_function_unit_basic':0,
        'chorioamnionitis':'No',
        'delayed_cord_clamping':'No',
        'rupture_of_membranes_rom_two':'<18 hours',
        'hypothermia_status_value':0,
        'oxygen_saturation':94,
        'breathing_rate':58,
        'x_ray_diagnosis_any_other':'NA',
        'baby_respiratory_support':'NA',
        'heart_rate':152,
        'urine_output':'Normal',
        'baby_blood_pressure_mean_arterial_bp':'NA',
        'baby_blood_pressure_upper_limb':'NA',
        'baby_blood_pressure_lower_limb':'NA',
        'two_d_echo_done_if_yes':'No',
        'frequency_of_stools':4,
        'baby_movement':'NA',
        'baby_thyroid_status':'Normal',
        'baby_thyroid_result':'NA',
        'baby_blood_glucose':'NA',
        'baby_haemoglobin_levels':21.1,
        'baby_c_reactive_protien_levels':23,
        'total_leucocute_count':0,
        'absolute_neutrophil_count':0,
        'thrombocytopenia':345435,
        'sodium':135,
        'potassium':47,
        'chlorine':345,
        'calcium':'NA',
        'magnesium':'NA',
        'urea':10.6,
        'creatinine':0.43,
        'lactate_levels':'NA',
        'bilirubin_levels':'NA',
        'cord_ph':'NA',
        'csf_culture_tsb_value':'NA'
}

response = requests.post('http://localhost:5000/getscore', data=data)
print(response.headers)
print('Score: --- ' + str(response.content).replace('b',''))
